import { Colours, Radius } from "@/src/constants/Theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: Colours.background,
  },
  contentBody: {
    flex: 1,
    flexDirection: "row",
  },
  leftColumn: {
    width: 70,
    backgroundColor: Colours.black,
  },
  dateItem: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 15,
  },
  selectedBar: {
    position: "absolute",
    left: 0,
    width: 4,
    height: "25%",
    backgroundColor: Colours.white,
    borderTopRightRadius: 2,
    borderBottomRightRadius: 2,
  },
  monthLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: Colours.secondaryText,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 4,
    opacity: 0.6,
  },
  monthLabelSelected: {
    color: Colours.white,
    opacity: 1,
  },
  dateText: {
    fontSize: 16,
    color: Colours.secondaryText,
    fontWeight: "600",
  },
  dateTextSelected: {
    color: Colours.white,
    fontWeight: "900",
    fontSize: 22,
  },
  rightColumn: {
    flex: 1,
    padding: 25,
    paddingTop: 10,
    backgroundColor: Colours.background,
    justifyContent: "center",
    gap: 50,
  },
  scentRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  labelWrapper: {
    alignItems: "center",
    marginRight: 20,
    width: 35,
  },
  slotLabel: {
    fontSize: 11,
    color: Colours.secondaryText,
    fontWeight: "900",
    opacity: 0.4,
    marginBottom: 8,
  },
  verticalLine: {
    width: 1,
    height: 50,
    backgroundColor: Colours.border,
    opacity: 0.2,
  },
  imageSlot: {
    flex: 1,
    height: 130,
    borderRadius: Radius.small,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colours.border,
  },
  emptySlot: {
    backgroundColor: Colours.transparentWhite,
    justifyContent: "center",
    alignItems: "center",
  },
  filledSlot: {
    backgroundColor: Colours.white,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: Colours.border,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  textDetailsSlot: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 12,
  },
  brandText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colours.secondaryText,
    textTransform: "uppercase",
    marginBottom: 4,
    opacity: 0.6,
    textAlign: "center",
  },
  nameText: {
    fontSize: 14,
    fontWeight: "800",
    color: Colours.primaryText,
    textAlign: "center",
    lineHeight: 18,
  },
  plusText: {
    fontSize: 24,
    color: Colours.primaryText,
    opacity: 0.2,
    fontWeight: "200",
  },
  perfumeImg: {
    width: "85%",
    height: "75%",
  },
  // [TEST]
  testFrame: {
    position: "absolute",
    bottom: 30,
    right: 15,
    borderWidth: 1,
    borderColor: Colours.border,
    borderStyle: "dashed",
    borderRadius: Radius.small,
    padding: 10,
    paddingTop: 18,
    backgroundColor: Colours.white,
    zIndex: 9999,
  },
  testLabelContainer: {
    position: "absolute",
    top: -10,
    left: 8,
    backgroundColor: Colours.black,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 2,
  },
  testLabelText: {
    color: Colours.whiteText,
    fontSize: 8,
    fontWeight: "900",
  },
  testButtonGroupInner: { flexDirection: "row", gap: 6 },
  testButtonLog: {
    backgroundColor: "#4A90E2",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Radius.small,
    minWidth: 60,
    alignItems: "center",
  },
  testButtonDelete: {
    backgroundColor: Colours.error,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Radius.small,
    minWidth: 60,
    alignItems: "center",
  },
  testButtonText: {
    color: Colours.whiteText,
    fontSize: 10,
    fontWeight: "800",
  },
});
